### ISSUE TITLE
Database exception at starup of an application with Mandarine 2.0.1

### ISSUE THREAD

**Issue by andreas-barthel** [mandarineorg/mandarinets#178]
**[Details]**
After update my project to Mandarine 2.0.1 some exceptions occurs on startup.

**[Stacktrace]**
```
 Mandarine.TS Framework :: 2.0.1

[INFO | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [MandarineCore.class] Starting framework with PID 23840
[WARN | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [MandarineCompiler.class] No `.env` file was found or it could not be read
[INFO | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [MandarineCore.class] A total of 1 repositories have been found
[INFO | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [MandarineMvcFrameworkStarter.class] Starting MVC Module
[WARN | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [AuthenticationRouting.class] Authentication Manager was not found or could not be satisfied
[INFO | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [SessionMiddleware.class] Session handler middleware has been initialized
[INFO | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [MandarineCore.class] A total of 1 controllers have been initialized
[ERROR | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [PostgresConnector.class] Database connection could not be reached
[ERROR | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [PostgresConnector.class] Query & connection have failed to be reached [
  [
    TypeError: Cannot read property 'query' of undefined
    at PostgresConnector.queryWithConnection (postgreSQLConnector.ts:79:55)
    at EntityManager.initializeAllEntities (entityManager.ts:85:68)
  ]
]
[ERROR | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [PostgresConnector.class] Query & connection have failed to be reached [
  [
    TypeError: Cannot read property 'query' of undefined
    at PostgresConnector.queryWithConnection (postgreSQLConnector.ts:79:55)
    at EntityManager.initializeAllEntities (entityManager.ts:86:68)
  ]
]
[ERROR | Wed Sep 02 2020 13:18:01 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [PostgresConnector.class] Query & connection have failed to be reached [
  [
    TypeError: Cannot read property 'query' of undefined
    at PostgresConnector.queryWithConnection (postgreSQLConnector.ts:79:55)
    at EntityManager.initializeAllEntities (entityManager.ts:87:68)
  ]
]
[INFO | Wed Sep 02 2020 13:18:02 GMT+0200 (Mitteleuropäische Sommerzeit)] [23840] [MandarineMVC.class] Server has started ~ http://0.0.0.0:8080
```

**[Scenario]**
1) Check out master branch of [https://github.com/andreas-barthel/mandarine-test](https://github.com/andreas-barthel/mandarine-test) 
2) Edit database connection in properties
3) Start application with `mandarine run --allow-env`

**[Expected behavior]**
Start of application without errors

**[OS]**
Windows 10 Pro 1909

**[Environment]**
 - Mandarine version **v2.0.1**
 - Mandarine CLI version **1.1.0**
 - Deno version  **1.3.2**
 - Deno v8 version **8.6.334**
 - Deno typescript version  **4.0.2**

**[Additional]**
If i try to save an entity to database after start of application, then this exception occurs:
```
[ERROR | Wed Sep 02 2020 13:24:44 GMT+0200 (Mitteleuropäische Sommerzeit)] [34224] [PostgresConnector.class] Database connection could not be reached
[ERROR | Wed Sep 02 2020 13:24:44 GMT+0200 (Mitteleuropäische Sommerzeit)] [34224] [PostgresConnector.class] Query statement could not be executed [
  [
    Error: Connection could not be made under query [object Object]
    at PostgresConnector.query (postgreSQLConnector.ts:68:31)
    at async PostgresRepositoryProxy.executeQuery (repositoryPostgresProxy.ts:27:38)
    at async PostgresRepositoryProxy.save (repositoryPostgresProxy.ts:65:33)
    at async MyController.httpHandlerAwait (helloWorld.ts:36:13)
    at async requestResolver (routingResolver.ts:36:46)
    at async responseHandler (mandarineMvcFrameworkStarter.ts:184:17)
    at async dispatch (middleware.ts:39:7)
    at async dispatch (middleware.ts:39:7)
    at async dispatch (middleware.ts:39:7)
    at async resourceHandlerMiddleware.ts:59:9
  ]
]
```

I think it's related to #176

**Comment by andreespirela** [comment]
After investigating a bit, `Database connection could not be reached` is thrown when your application doesn't reach the pool connection. https://github.com/mandarineorg/mandarinets/blob/7fb08b8971c76b2e060ef4f99a11dec9004c2a55/orm-core/connectors/postgreSQLConnector.ts#L61 . 

Can you double check all your connection parameters are ok?. Uppercase, lowercase, typos, properties name in the properties.json. Thanks

**Comment by andreas-barthel** [comment]
Hi @andreespirela 
Sorry, it was a typo in the properties. Works fine now.
